documents_path : ./documents
db_embedding_path : ./embedding_models/bge-base-en-v1.5.Q8_0.gguf
cross_encoder_path : ./cross-encoder-models/ms-marco-TinyBERT-L-6-v2
chat_model_path : ./chat_models/Phi-3-mini-4k-instruct-q4.gguf